# Generated by Django 4.1 on 2022-09-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
